# Python review

Short review about some core concepts in Python exemplified by objects in the Numpy library.

Goals:

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and packages

**library:** a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:** 

- core library for numerical computing in Python
- many libraries use NumPy arrays as their building blocks
- computations on NumPy objects are omptimized for speed and memory usage

Let's import NumPy with its **standard abbreviation** `np`:

In [2]:
import numpy as np

## Variables

**variable:** a name we assign to a particular object in Python

Example:

In [3]:
# Assign a small array to variable a
a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's value from our Jupyter notebook:

In [4]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print value
print(a)

[[1 1 2]
 [3 5 8]]


## Naming convention: use `snake_case` for naming variables.

This is the convention we will use in this course. Why? `my-variable` or `MyVariable` or `myVariable`, 
PEP 8 - Style Guide for Python Code recommends snake_case.

**Remember** that variable names should both be descriptive and concise!

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific.
Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

In practice, we can often use the word variable and object interchangeably. 

## Types

Every object in Python has a **type**. The type tells us what kind of object we have. 
We can also call the type of an object, the **class** of an object. So, type and class both mean the kind of object we have. 

In [6]:
print(a)

[[1 1 2]
 [3 5 8]]


In [7]:
# See the type/class of a variable/object by using the `type` function

In [8]:
type(a)

numpy.ndarray

The `numpy.ndarray` is the core object/data type of the NumPy package.

In [10]:
print(a[0,0])

type(a[0,0])

1


numpy.int64

`numpy.int64` is not the standard Python integer type `int`.

`numpy.int64` is a special data type in NumPy telling us that 1 is an integer stored as a 64-bit number.

Check-in: acces the value 5 in array `a`.

In [12]:
print(a[1,1])

5


## Functions

`print` was our first example of a Python **function**

Functions take in a set of **arguments**, separated by commas, and use those arguments to create an **output**.

In this course, we'll be using argument and parameter interchangeably. But they do have slightly different meanings.

We can ask for information about what a function does by executing `?` followed by the function name:

In [13]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring**, a special type of comment that is used to document how a function (or a class or module) works.

Notice that there are different types of arguments inside the function's parenthesis.

Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments that *you* have to specify for the function to work

- **optional arguments**: arguments that are pre-filled wtih a default value by the function, but you can override them. Optional arguments appear inside the parentheses in the form `optional_argument = default_value`

Example:

`end` is a parameter in `print` with default value in a new line.
We can pass the value `:)` to this parameter so that it finishes the line with `:)` instead

In [15]:
print("Change the end parameter", end=':)')

Change the end parameter:)

## Attributes and methods

An object in Python has attributes and methods.

- **attribute**: a property of the object, some piece of information about it
- **method**: a procedure associated with an object, actions that the object does

Example: for class cat, the attributes would be name, color, age, weight, etc. The cat's methods would be meow(), nap(), chase_laser(), etc.

Example:

NumPy arrays have many methods and attributes. For example:

In [16]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [18]:
# T is an example of an attribute, it returns the transpose of the array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [19]:
type(a.T)

numpy.ndarray

In [27]:
# Shape is another attribute that tells us the shape of the array
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [26]:
# ndim is an attribute holding the number of array dimensions
print("dim:", a.ndim, "| type:", type(a.ndim))

dim: 2 | type: <class 'int'>


Attributes for the same object can have many different types.

Some examples of methods:

In [29]:
# The min method returns the minimum value in the array along a specified axis.
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [30]:
# Run min method without axis
a.min()

1

Remember that methods are functions associated with an object. We can confirm this:

In [31]:
# method tolist() transforms array into a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [36]:
type(a.tolist)

builtin_function_or_method

In [41]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [39]:
x = 77
y = "99"

In [42]:
print(x,y,x,sep="%")

77%99%77
