# Python review

Short review about some core concepts in Python exemplified by objects in the Numpy library.

Goals:

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and packages

**library:** a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:** 

- core library for numerical computing in Python
- many libraries use NumPy arrays as their building blocks
- computations on NumPy objects are omptimized for speed and memory usage

Let's import NumPy with its **standard abbreviation** `np`:

In [1]:
import numpy as np

## Variables

**variable:** a name we assign to a particular object in Python

Example:

In [3]:
# Assign a small array to variable a
a = np.array([ [1,1,2], [3,5,8] ])

To view a variable's value from our Jupyter notebook:

In [4]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print value
print(a)

[[1 1 2]
 [3 5 8]]
